### ISSUE TITLE
Texts to select translate modes are not localized

### ISSUE THREAD

**Issue by sypets** [web-vision/wv_deepltranslate#15]
The backend user only sees texts for selecting the translate mode in English, even if different language is selected. (For the description, a localized string is used though, just not for the button)

![image](https://user-images.githubusercontent.com/13206455/120785869-dd2f5900-c52d-11eb-9a4b-30ffa5b04176.png)

The texts are directly written as strings in `Resources/Public/JavaScript/Localization.js` and not localized.

Unfortunately, this is the same thing in the core: https://forge.typo3.org/issues/94277

I am not sure, but I think you can use localized strings in the TYPO3 JavaScript API.

**Comment by ayacoo** [comment]
@sypets I think I would open a branch here for the translations in general. There are 1-2 places to catch up. It probably makes sense if our pull requests are noticed. I had let Web Vision know.

In addition, so that we are not dependent on the TYPO3 patch, I would leave it up to the extension itself to translate. Otherwise older TYPO3 versions would have empty labels there.

**Comment by sypets** [comment]
@ayacoo Thanks!
