### ISSUE TITLE
not compatible with extension recordlist_thumbnail

### ISSUE THREAD

**Issue by Hobokens** [web-vision/wv_deepltranslate#151]
The extension `recordlist_thumbnail` allows the display of thumbnails in the list view, which was standard until version TYPO3 10.

wv_deepltranslate prevents the extension from displaying thumbnails.

**Comment by calien666** [comment]
* Affected TYPO3 version: 11 and above
* installed ext: https://github.com/studiomitte/recordlist_thumbnail

This is because recordlist_thumbnail x-classes the DatabaseRecordList, as we do, too. 
https://github.com/studiomitte/recordlist_thumbnail/tree/main/Classes/Xclass

It would a big impact, overriding the Xlcass in this extension, because we can't consider side effects.

If you want to have both features implemented, please xlcass by your own, but be aware, we can't handle possible side effects.

See https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Breaking-92118-TCACtrlThumbnailSettingDropped.html
