### ISSUE TITLE
stability & tests vs. new features

### ISSUE THREAD

**Issue by sypets** [web-vision/wv_deepltranslate#154]
I am a bit concerned with stability currently. Right now there are 3 core versions supported, additionally, there are still PHP 8.1 bugs to be fixed. There are no (regularly running) test and there are various variants (the TYPO3 and PHP versions) and functionality that need to be tested.

Additionally, some of the bugs break basic core functionality, without even using the translations or glossary.

New features are introduced and major refactoring, without running tests or even phpstan.

My urgent request: please make wv_deeplglossary stable and add tests before adding new features. Would still prefer glossary functionality in separate extension - not just because of the instabilty currently, but also because of flexibility of using the included glossary vs. managing glossary otherwise.

Please test (manually and automatic tests) with PHP 11 and 8.1 and with several languages. There is already a PR here: #147

It probably also makes sense to drop v9 and v10 support before adding extensive new features.

**Comment by Riiiad** [comment]
Thank you for bringing up your concerns regarding stability. We understand how important it is to have a stable system, and we are actively working on addressing the issues you mentioned. Our team is currently focused on fixing the major bugs causing the instability, which is also the reason for the significant refactorings. We are also working on improving our test setup to ensure that the system functions properly. However, implementing reliable automated tests is a chapter on it own and needs time and effort.

We want to assure you that we are committed to providing a stable and reliable system, but due to the limited amount of time we have available, some improvements may take longer to implement. We appreciate your patience and understanding as we work towards resolving these issues.

**Comment by calien666** [comment]
@datango The code version 3.3.0 is a bug, which will be corrected before next release. We are working on it, to make a new release as fast as possible. Unfortunately, some project work binds us since weeks, so we where not able to find time work here.

**Comment by sbuerk** [comment]
I guess, we could close this issue for now.

* CI testing has been introduced already for 3.x (#147)
* CI testing for 4.x is changed to use core testing-framework with tightend settings to test harder on things (#231)

Granted, there have been heavy restructing work going on, but at least for the 3.x this is now stabalized. `4.x` will get further restructing, due to the fact as supported core version changed.

Beside this, it's already planned to add more tests to cover the code base more tighten, which is already a mile-stone/issue for itself.

@sypets @datango Would it be okay to close the issue ?

**Comment by calien666** [comment]
As no reaction on this issue, I will close here. Feel free to open a new one, if you think, this might be wrong.
