### ISSUE TITLE
403 error after update to v2.3.1 (TYPO3 10.4)

### ISSUE THREAD

**Issue by dkd-lehnebach** [web-vision/wv_deepltranslate#166]
We are running a TYPO3 10.4 installation with version 2.2.2 of your extension and a deepl v2 api key. Everything was working fine until we updated wv_deepltranslate to version 2.3.1. Now we're getting: 
{"status":"false","message":"Client error:GET https:\/\/api.deepl.com\/v2\/languages?type=target resulted in a 403 Forbiddenresponse"}" when calling any page in the TYPO3 backend. After downgrading the extension everything is working again.

Do you have any hint what the problem could be?

Best regards
Florian

**Comment by calien666** [comment]
@dkd-lehnebach Are you using DeepL Pro or Free API version?

**Comment by dkd-lehnebach** [comment]
I'm using the Pro API Version

**Comment by abeutel** [comment]
I ran into the same problem and did a quick debug. In my environment the Curl exception was caused by `DeeplService->loadSupportedLanguagesFromAPI()` because the extension configuration (retrieved in the constructor) did not take my override settings from `.env` into account and fell back to the settings from `LocalConfiguration.php` where no API-Key/API-URL was set. Did not dig deeper so far.

**Comment by calien666** [comment]
@dkd-lehnebach @abeutel We released v3. Could you just test, if your issue is still appearing? We tested even the usage of the API key set in .env and had no problems. Hope this helps.

**Comment by calien666** [comment]
As no reaction on this issue, I will close here. Feel free to open a new one, if you think, this might be wrong.
