### ISSUE TITLE
Translate DCE element

### ISSUE THREAD

**Issue by vbuilt** [web-vision/wv_deepltranslate#34]
Hi,

Thank you so much for this awesome extension with the cool translating options.

Is this possible to make translation for the DCE (dynamic content element) elements?

Please share your thought on it asap.

Thanks again
Team Vbuilt Solution

**Comment by MajPay** [comment]
I was asked to install this extension in a project where DCE has been used. It seems the problem is within DCE and not wv_deepltranslate. DCE seems to alwas render the fields in a pi_flexform field even if you map those fields on tca fields.

So part 1 of this issue: DCE is incompatible with wv_deeptranslate. I will finally migrate away from that dce crap.
part 2 of this issue: wv_deeptranslate can not handle pi_flexform fields. And by looking into TYPO3 DataHandler it seems it wont be able to because typo3 calls the Hook only for text and input fields.

So there is nothing wv_deeptranslate could add to change anything here...

**Comment by NarkNiro** [comment]
It is currently not planned to support DCE with the DeepL Extension. Because they are exclusively FlexForm fields and
we would first have to think about it, but as already written here, this is probably that simple.

But a pull request to the theme is always welcome. :)
