### ISSUE TITLE
Translate to EN-GB or EN-US

### ISSUE THREAD

**Issue by kkugelmann** [web-vision/wv_deepltranslate#92]
From what I saw there is not possibility to specify wether to translate to EN, EN-GB or EN-US as the extension is only using the two letter ISO code from the site config to determine the target language.

As an idea: Would it be possible to use the field with the RFC 1766 / 3066 definition as the value and fall back to the ISO 369-1 field?

**Comment by ahobitt** [comment]
It would be really great to be able to choose British English as well. The default value with "en" is unfortunately American English, as far as I can see.

**Comment by sypets** [comment]
@calien666 Is that not configured in BE module "Deepl" > "Settings"? (not Extension Configuration)?

![image](https://user-images.githubusercontent.com/13206455/215066505-ead368a7-3239-4cc0-9368-9d9f5e38f8a3.png)

![image](https://user-images.githubusercontent.com/13206455/215066601-ccfe1aec-6e2d-437f-9bc9-b3f87e2a435c.png)

I vaguely remember having changed that a while ago on our site, because we use British English as target language.

I used the following text:

German
> Ich habe vor, heute noch Benzin zu kaufen. Der Laster ist sehr schmutzig. Danach esse ich einen Keks in meiner Wohnung.

Is translated to:

> I plan to buy **petrol** today. The **truck** is very dirty. Afterwards I'm going to eat a **biscuit** in my **flat**.

petrol is pretty British (Americans use gas or gasoline), "truck" is more American (Brits use "lorry"), "biscuit" is British (Americans use cookie). "flat" is British (Americans use "appartment" or "condo" etc.).

So I would say, the result is (mostly) British.

**Comment by calien666** [comment]
@sypets We are working on it and will have a look these days. I just wanted to make a clean issue to PR scenario.

Thanks for some German sentences to test.

**Comment by sypets** [comment]
@calien666 Thanks.

My point is I am not sure if the PR #106 makes that much sense because it adds something to the "Extension Configuration" (ext_conf_template.txt) which might already be there in the DeepL Settings BE module. 

But I may be wrong and I don't know exactly what the PR is trying to do and unfortunately there is no description. 

Btw, I tried to find the "DeepL Settings" in the documentation. It is listed here: 

https://github.com/web-vision/wv_deepltranslate/blob/master/Documentation/UsersManual/Index.rst#deepl-module-settings
but not in the README.

**Comment by NarkNiro** [comment]
We merged the PR #107 it was the better solution.
